"""
Synthesis Agent.

Receives all findings and IOCs gathered by other agents,
and calls Gemini to synthesize a final executive summary report.
"""

from __future__ import annotations

from langchain_core.messages import AIMessage

from bastion.logger import get_logger
from bastion.models.state import BastionState

logger = get_logger(__name__)

SYNTHESIS_SYSTEM_PROMPT = """\
You are an elite Lead Incident Responder of the BASTION Autonomous SOC.
Your job is to read all findings, IOCs, and Athena SQL forensic results collected by your sub-agents,
and synthesize them into a highly professional, structured Executive Markdown Report.

CRITICAL INSTRUCTIONS:
Always use this exact Markdown structure for your final response. Use bolding, tables, and code blocks where appropriate. Do not output anything outside of this structure. ENSURE YOU COMPLETE THE ENTIRE RESPONSE.

# 🛡️ BASTION Security Incident Report
**Date:** [Generate current UTC date] | **Verdict:** [CRITICAL COMPROMISE / HIGH RISK / FALSE POSITIVE]

## 1. Executive Summary
[A concise 2-3 sentence overview of what happened, who is affected, and the immediate business impact.]

## 2. Attack Scenario (Kill Chain)
[Bullet points narrating the chronological sequence of the attack based on Forensic and Email agent findings.]
- **Initial Access:** [details]
- **Execution / Persistence:** [details]
- **Exfiltration / Impact:** [details]

## 3. Indicators of Compromise (IOCs)
[If there are IOCs, format them in a Markdown Table exactly like this:]
| Indicator Type | Value | Context | Threat Intel Rep |
|---|---|---|---|
| IP Address | 185.220.101.45 | Source IP in forensic investigation | VT: 15/94 Malicious, AbuseIPDB: 87% Confidence |

CRITICAL RULES for the "Threat Intel Rep" column:
- If the findings contain VirusTotal data (look for "source": "VirusTotal" or "virustotal_v3_api", or "malicious_count", "detection_ratio", "last_analysis_stats"), you MUST write: "VT: X/Y Malicious" where X is malicious count and Y is total engines.
- If the findings contain AbuseIPDB data (look for "source": "AbuseIPDB" or "abuse_confidence_score"), you MUST write: "AbuseIPDB: Z% Confidence" where Z is the abuse confidence score.
- If BOTH sources are present, combine them: "VT: X/Y Malicious, AbuseIPDB: Z% Confidence"
- If the IP is RFC 1918 private (10.x.x.x, 172.16-31.x.x, 192.168.x.x), write: "Internal Network"
- If no threat intel data is available, write: "No Data Available"
- NEVER write "UNKNOWN" or "UNKNOWN (Invalid Format)" — always provide a specific assessment.
[If there are NO IOCs, explicitly write "None detected."]

## 4. Detection Logic (Sigma Rule)
[Write a brief, valid Sigma rule block in YAML format to detect this behavior in the future. If not applicable, write "Not applicable."]
```yaml
title: Autogenerated Threat Detection
logsource:
   ...
detection:
   ...
```

## 5. Containment & Remediation
[3-4 concrete, actionable steps the SOC team must take immediately]
"""

def synthesis_node(state: BastionState) -> dict:
    """Synthesis node for LangGraph."""
    log = logger.bind(agent="synthesis", event_type=state.get("event_type"))
    log.info("synthesis.start")

    findings = state.get("findings", [])
    iocs = state.get("iocs", [])

    if not findings and not iocs:
        return {
            "final_report": "No significant findings or anomalies detected during analysis.",
            "messages": [AIMessage(content="[Synthesis] No findings to report.")],
            "pipeline_logs": [{"node": "synthesis", "action": "Analysis complete", "detail": "No significant findings or IOCs detected. Event appears benign.", "ts": __import__('datetime').datetime.now(__import__('datetime').timezone.utc).isoformat()}],
        }

    try:
        user_message = (
            f"Please synthesize the following security findings into a final report:\n\n"
            f"Findings: {findings}\n\n"
            f"IOCs: {iocs}"
        )

        from bastion.services.gemini import call_gemini

        final_report = call_gemini(
            prompt=user_message,
            system_prompt=SYNTHESIS_SYSTEM_PROMPT,
        )

        log.info("synthesis.complete", report_length=len(final_report))

        # Calculate a rough risk score based on severities
        score = 0.0
        for f in findings:
            sev = str(f.get("severity", "LOW")).upper()
            if sev == "CRITICAL": score += 0.4
            elif sev == "HIGH": score += 0.25
            elif sev == "MEDIUM": score += 0.15
            elif sev == "LOW": score += 0.08
            elif sev == "INFO": score += 0.05
            else: score += 0.1  # Unknown severity gets moderate score
        
        # Add bonus score for IOCs discovered
        ioc_bonus = min(0.2, len(iocs) * 0.03)
        score += ioc_bonus
        
        # Ensure at least a base risk when findings exist
        if findings and score < 0.15:
            score = 0.15
            
        risk_score = min(1.0, score)

    except Exception:
        log.exception("synthesis.error")
        final_report = "Error generating final synthesis report."
        risk_score = 0.5

    return {
        "final_report": final_report,
        "risk_score": risk_score,
        "messages": [AIMessage(content="[Synthesis] Final report generated successfully.")],
        "pipeline_logs": [
            {"node": "synthesis", "action": "Generating executive report", "detail": f"Synthesizing {len(findings)} findings and {len(iocs)} IOCs into executive summary via Gemini LLM", "ts": __import__('datetime').datetime.now(__import__('datetime').timezone.utc).isoformat()},
            {"node": "synthesis", "action": "Risk score computed", "detail": f"Final risk score: {(risk_score*100):.0f}% — Report length: {len(final_report)} chars", "ts": __import__('datetime').datetime.now(__import__('datetime').timezone.utc).isoformat()},
        ],
    }
