"""
Sigma / YARA rule auto-generation for the Forensic Analyst Agent.

Generates Sigma-format detection rules based on forensic findings,
enabling automated defense and SIEM integration.
"""

from __future__ import annotations

from datetime import datetime, timezone

from bastion.agents.forensic_analyst.models import ForensicAnalysisOutput
from bastion.logger import get_logger

logger = get_logger(__name__)

_SIGMA_TEMPLATE = """\
title: {title}
id: bastion-auto-{rule_id}
status: experimental
description: >-
  {description}
  Auto-generated by BASTION Forensic Analyst Agent.
author: BASTION
date: {date}
logsource:
  product: aws
  service: cloudtrail
detection:
  selection:
{selection_yaml}
  condition: selection
{filter_yaml}
falsepositives:
  - Legitimate administrative actions during maintenance windows
  - Authorized security testing
level: {level}
tags:
{tags_yaml}
"""


def generate_sigma_rule(
    findings: ForensicAnalysisOutput,
    flagged_events: list[dict] | None = None,
    source_ips: list[str] | None = None,
    user: str = "",
) -> str:
    """Generate a Sigma detection rule from forensic findings.

    Args:
        findings: The forensic analysis output with kill-chain and MITRE mappings.
        flagged_events: Specific CloudTrail events that triggered the detection.
        source_ips: Suspicious source IPs to include in the rule.
        user: Username involved in the incident.

    Returns:
        Sigma rule as a YAML string.
    """
    log = logger.bind(component="sigma_generator")

    # Build title
    tactics_str = ", ".join(findings.mitre_tactics[:3]) if findings.mitre_tactics else "Unknown"
    title = f"Detect {findings.status} - {tactics_str}"
    if user:
        title += f" (User: {user})"

    # Build description
    kill_chain_str = " -> ".join(findings.kill_chain_identified) if findings.kill_chain_identified else "N/A"
    description = (
        f"Detects attack pattern: {kill_chain_str}. "
        f"Status: {findings.status}, Confidence: {findings.confidence_score:.0%}."
    )

    # Build detection selection
    selection_lines: list[str] = []

    event_names = set()
    if flagged_events:
        for evt in flagged_events:
            name = evt.get("eventName", "")
            if name:
                event_names.add(name)

    if event_names:
        selection_lines.append("    eventName:")
        for name in sorted(event_names):
            selection_lines.append(f"      - '{name}'")

    if source_ips:
        selection_lines.append("    sourceIPAddress:")
        for ip in source_ips:
            selection_lines.append(f"      - '{ip}'")

    if user:
        selection_lines.append(f"    userIdentity.userName: '{user}'")

    if not selection_lines:
        selection_lines.append("    eventName: 'AssumeRole'")

    selection_yaml = "\n".join(selection_lines)

    # Filter (reduce false positives)
    filter_lines = []
    if user:
        filter_lines.append(f"  filter:")
        filter_lines.append(f"    userIdentity.userName|not: '{user}'")
    filter_yaml = "\n".join(filter_lines) if filter_lines else ""

    # Level mapping
    level_map = {
        "CRITICAL_COMPROMISE": "critical",
        "HIGH_RISK": "high",
        "MEDIUM_RISK": "medium",
        "LOW_RISK": "low",
        "CLEAN": "informational",
    }
    level = level_map.get(findings.status, "medium")

    # MITRE tags
    tags_lines = []
    for tactic in findings.mitre_tactics:
        tags_lines.append(f"  - attack.{tactic.lower()}")
    for stage in findings.kill_chain_identified:
        safe_tag = stage.lower().replace(" ", "_").replace("(", "").replace(")", "")
        tags_lines.append(f"  - attack.{safe_tag}")
    tags_yaml = "\n".join(tags_lines) if tags_lines else "  - attack.unknown"

    # Generate rule ID from timestamp
    rule_id = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    date = datetime.now(timezone.utc).strftime("%Y/%m/%d")

    sigma_rule = _SIGMA_TEMPLATE.format(
        title=title,
        rule_id=rule_id,
        description=description,
        date=date,
        selection_yaml=selection_yaml,
        filter_yaml=filter_yaml,
        level=level,
        tags_yaml=tags_yaml,
    )

    log.info(
        "sigma.rule_generated",
        title=title,
        level=level,
        event_names=list(event_names),
    )

    return sigma_rule.strip()
